### ISSUE TITLE
November Revision to-do

### ISSUE THREAD

**Issue by rBatt** [rBatt/trawlDiversity#1]
- [x] Categories and range in richness/ initial-final richness. Can "colonizers" explain changes in richness?

- [x]  As suggested by @mtingley, we should report (1) the average number of tows per site per year, and the maximum number of tows per site per year. (2) The number of sites per region (ranges)

- [x] For which regions did we use truncated time series? In most regions I believe the sampling frequency and location was the most important factor for choosing to drop years. In other regions it may have been the large number of initial colonizations, e.g. EBS.

- [x] Define how day of year was adjusted for each region, and pair with density plots for number of hauls (y axis) vs day of year, and a different line for each year

- [x] List which species were removed, and why?

- [x] Effect on bin size (lon-lat and depth) on number of sites sampled

**Comment by rBatt** [comment]
This describes bin size pretty well I think:

![bin_size_scaled-1](https://cloud.githubusercontent.com/assets/5630847/20402847/61e49612-accc-11e6-8bb2-96610d780700.png)

**Comment by rBatt** [comment]
Here's a table that answer @mtingley 's question regarding sites per region and tows per site-year. Added this table to the manuscript report in last commit (a1c33c6)

Years = Total number of years sampled, Year Range = the minimum and maximum of years sampled, Year Interval = the number of years elapsed between samples (and the frequency of this interval in parentheses), Sites = the total number of sites in the region, Max. Tows = maximum number of tows per site per year, Average Tows = the average number of tows per site per year, Total Species = the total number of species observed in the region across all sites and years.

| Region | Years | Year Range | Year Interval | Sites | Max. Tows | Average Tows | Total Species |
| :-- | --: | :-- | :-- | --: | --: | --: | --: |
| ai | 12 | 1983 - 2014 | 2(5), 3(4), 4(1), 5(1) | 82 | 12 | 2.83 | 55 |
| ebs | 31 | 1984 - 2014 | 1(30) | 138 | 4 | 1.59 | 110 |
| gmex | 17 | 1984 - 2000 | 1(16) | 39 | 39 | 5.65 | 144 |
| goa | 13 | 1984 - 2013 | 2(7), 3(5) | 89 | 15 | 4.35 | 98 |
| neus | 32 | 1982 - 2013 | 1(31) | 100 | 10 | 2.99 | 141 |
| newf | 16 | 1996 - 2011 | 1(15) | 191 | 9 | 2.24 | 72 |
| sa | 25 | 1990 - 2014 | 1(24) | 24 | 13 | 3.87 | 104 |
| shelf | 41 | 1970 - 2010 | 1(40) | 48 | 11 | 2.52 | 48 |
| wctri | 10 | 1977 - 2004 | 3(9) | 84 | 91 | 4.66 | 92 |
